// Generated by CoffeeScript 1.6.1
(function() {

  window.displayed = {};

  $(document).ready(function() {
    return chrome.history.search({}, function(history) {
      return chrome.tabs.query({}, function(tabs) {
        var link, tab, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = tabs.length; _i < _len; _i++) {
          tab = tabs[_i];
          if (!(history.indexOf(tab.id) !== -1)) {
            continue;
          }
          link = history["" + tab.id];
          window.display(link);
          window.displayed["" + link.id] = true;
          _results.push(chrome.history.getVisits({
            'url': link.url
          }, function(visits) {
            var visit, _j, _len1, _results1;
            _results1 = [];
            for (_j = 0, _len1 = visits.length; _j < _len1; _j++) {
              visit = visits[_j];
              if (!(visit.visitId === link.id)) {
                continue;
              }
              window.display(history["" + visit.referringVisitId], link.id);
              _results1.push(window.displayed["" + visit.referringVisitId] = true);
            }
            return _results1;
          }));
        }
        return _results;
      });
    });
  });

  /*
  
  	HistoryItem
  
  	id ( string )
  		The unique identifier for the item.
  	url ( optional string )
  		The URL navigated to by a user.
  	title ( optional string )
  		The title of the page when it was last loaded.
  	lastVisitTime ( optional double )
  		When this page was last loaded, represented in milliseconds since the epoch.
  	visitCount ( optional integer )
  		The number of times the user has navigated to this page.
  	typedCount ( optional integer )
  		The number of times the user has navigated to this page by typing in the address.
  
  	VisitItem
  
  	id ( string )
  		The unique identifier for the item.
  	visitId ( string )
  		The unique identifier for this visit.
  	visitTime ( optional double )
  		When this visit occurred, represented in milliseconds since the epoch.
  	referringVisitId ( string )
  		The visit ID of the referrer.
  */


}).call(this);
