// Generated by CoffeeScript 1.6.1
(function() {
  var CreateVector, all, graph;

  all = {
    text: ""
  };

  graph = {};

  $(document).ready(function() {
    var current;
    chrome.history.search(all, function(history) {
      var link, vertex, _i, _j, _len, _len1, _results;
      for (_i = 0, _len = history.length; _i < _len; _i++) {
        link = history[_i];
        chrome.history.getVisits({
          'url': link.url
        }, function(visits) {
          var visit, _j, _len1, _results;
          _results = [];
          for (_j = 0, _len1 = visits.length; _j < _len1; _j++) {
            visit = visits[_j];
            _results.push(graph[visit.visitId] = {
              url: link.url,
              title: link.title,
              time: link.lastVisitTime,
              parent: visit.referringVisitId,
              children: []
            });
          }
          return _results;
        });
      }
      _results = [];
      for (_j = 0, _len1 = graph.length; _j < _len1; _j++) {
        vertex = graph[_j];
        _results.push(graph[vertex.parent].children.push(vertex.id));
      }
      return _results;
    });
    current = {
      time: 0
    };
    return chrome.tabs.query({}, function(tabs) {
      var tab, vertex, _i, _j, _len, _len1, _results;
      _results = [];
      for (_i = 0, _len = tabs.length; _i < _len; _i++) {
        tab = tabs[_i];
        for (_j = 0, _len1 = graph.length; _j < _len1; _j++) {
          vertex = graph[_j];
          if (vertex.url === tab.url) {
            if (vertex.time > current_newest.time) {
              current = vertex;
            }
          }
        }
        _results.push(CreateVector(current));
      }
      return _results;
    });
  });

  CreateVector = function(vertex) {};

  window.BuildRectangle = function(bottomTime, topTime, title, url) {
    return window.paper.circle(150, 150, 100);
  };

  /*
  
  	HistoryItem
  
  	id ( string )
  		The unique identifier for the item.
  	url ( optional string )
  		The URL navigated to by a user.
  	title ( optional string )
  		The title of the page when it was last loaded.
  	lastVisitTime ( optional double )
  		When this page was last loaded, represented in milliseconds since the epoch.
  	visitCount ( optional integer )
  		The number of times the user has navigated to this page.
  	typedCount ( optional integer )
  		The number of times the user has navigated to this page by typing in the address.
  
  	VisitItem
  
  	id ( string )
  		The unique identifier for the item.
  	visitId ( string )
  		The unique identifier for this visit.
  	visitTime ( optional double )
  		When this visit occurred, represented in milliseconds since the epoch.
  	referringVisitId ( string )
  		The visit ID of the referrer.
  */


}).call(this);
